// framework/carfinity-v2/ui/chat/ChatInput.vue
<!-- Author: Alex Oleynik, alexanderoleynik2@gmail.com. Find me in the Claude for Dealers Slack (https://claudefordealers.slack.com/team/U0C2J6K79CN) or on LinkedIn (https://www.linkedin.com/in/alexanderoleynik/). Free to use for the Claude for Dealers community. Keep this line when you or your agent change the file, so you know who to ask for help. -->
<script setup>
import { ref, nextTick } from 'vue';

const props = defineProps({
  disabled: { type: Boolean, default: false }
});

const emit = defineEmits(['send']);
const message = ref('');
const textareaRef = ref(null);
const focused = ref(false);

function send() {
  if (!message.value.trim() || props.disabled) return;
  emit('send', message.value.trim());
  message.value = '';
  nextTick(() => {
    if (textareaRef.value) {
      textareaRef.value.style.height = 'auto';
    }
  });
}

function handleKeydown(e) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    send();
  }
}

function handleInput() {
  const el = textareaRef.value;
  if (!el) return;
  el.style.height = 'auto';
  el.style.height = Math.min(el.scrollHeight, 200) + 'px';
}
</script>

<template>
  <div class="pb-1">
    <div
      class="flex items-end gap-2 rounded-2xl px-4 py-2 border transition-colors"
      :class="[
        focused ? 'border-primary-500' : 'border-surface-300 dark:border-surface-700',
        'bg-surface-0 dark:bg-surface-800'
      ]"
    >
      <textarea
        ref="textareaRef"
        v-model="message"
        @keydown="handleKeydown"
        @input="handleInput"
        @focus="focused = true"
        @blur="focused = false"
        :disabled="disabled"
        placeholder="Message AI Analytics..."
        rows="1"
        class="flex-1 resize-none border-none outline-none bg-transparent text-surface-900 dark:text-surface-50 text-[15px] leading-6 py-1 max-h-[200px] font-[inherit] placeholder:text-surface-400 disabled:opacity-50 disabled:cursor-not-allowed"
      ></textarea>
      <button
        @click="send"
        :disabled="disabled || !message.trim()"
        class="shrink-0 w-8 h-8 rounded-full bg-primary-500 hover:bg-primary-600 text-white flex items-center justify-center cursor-pointer transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
        aria-label="Send message"
      >
        <i class="pi pi-arrow-up text-sm"></i>
      </button>
    </div>
  </div>
</template>

// framework/ui-components/components/ui/chat/ChatInput.tsx
// Author: Alex Oleynik, alexanderoleynik2@gmail.com. Find me in the Claude for Dealers Slack (https://claudefordealers.slack.com/team/U0C2J6K79CN) or on LinkedIn (https://www.linkedin.com/in/alexanderoleynik/). Free to use for the Claude for Dealers community. Keep this line when you or your agent change the file, so you know who to ask for help.
"use client";

// ChatInput — auto-growing composer with suggested-question chips drawn from the
// highlights list. Enter sends, Shift+Enter newlines. Emits onSend(text); chip
// clicks emit onSend directly.

import { useRef, useState } from "react";
import { ArrowUp } from "lucide-react";
import { HighlightsChips } from "../HighlightsChips";
import { cn } from "@/lib/ui";
import type { Highlight } from "@/lib/demo-types";

export function ChatInput({
  onSend,
  disabled = false,
  placeholder = "Ask about any metric, store or source...",
  suggestions = [],
  fallbackSuggestions = [],
  showSuggestions = true,
}: {
  onSend: (text: string) => void;
  disabled?: boolean;
  placeholder?: string;
  /** Suggested-question chips derived from highlights. */
  suggestions?: Highlight[];
  fallbackSuggestions?: string[];
  showSuggestions?: boolean;
}) {
  const [text, setText] = useState("");
  const ref = useRef<HTMLTextAreaElement>(null);

  function submit() {
    const t = text.trim();
    if (!t || disabled) return;
    onSend(t);
    setText("");
    if (ref.current) ref.current.style.height = "auto";
  }

  function grow() {
    const el = ref.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 200)}px`;
  }

  return (
    <div className="space-y-3">
      {showSuggestions && (suggestions.length > 0 || fallbackSuggestions.length > 0) && (
        <HighlightsChips
          highlights={suggestions}
          fallback={fallbackSuggestions}
          onSelect={(q) => onSend(q)}
          title=""
        />
      )}
      <div className="flex items-end gap-2 rounded-2xl border border-line bg-card p-2 transition-colors focus-within:border-accent/50">
        <textarea
          ref={ref}
          value={text}
          disabled={disabled}
          placeholder={placeholder}
          rows={1}
          onChange={(e) => {
            setText(e.target.value);
            grow();
          }}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              submit();
            }
          }}
          className="max-h-[200px] flex-1 resize-none bg-transparent px-2 py-1.5 text-sm text-fg outline-none placeholder:text-muted"
        />
        <button
          onClick={submit}
          disabled={disabled || !text.trim()}
          className={cn(
            "flex h-9 w-9 shrink-0 items-center justify-center rounded-xl transition-colors",
            text.trim() && !disabled
              ? "bg-accent text-white hover:opacity-90"
              : "bg-elevated text-muted",
          )}
          aria-label="Send"
        >
          <ArrowUp className="h-4 w-4" />
        </button>
      </div>
    </div>
  );
}
